#!/bin/bash

cp /usr/share/ovmf/ovmf_vars_x64.bin /tmp/ovmf_vars.bin
qemu-system-x86_64 \
  -enable-kvm \
  -m 1024 \
  -cpu host,kvm=off \
  -smp 2,sockets=1,cores=2,threads=1 \
  -device vfio-pci,host=01:00.0,x-vga=on \
  -device vfio-pci,host=01:00.1 \
  -drive if=pflash,format=raw,readonly,file=/usr/share/ovmf/ovmf_code_x64.bin \
  -drive if=pflash,format=raw,file=/tmp/ovmf_vars.bin \
  -vga none
